// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.

#pragma once

// [MuffMode] Shared module includes for MuffMode-only systems.
#include "mm_vote_types.h"
#include "mm_admin.h"
#include "mm_announcer.h"
#include "mm_arena.h"
#include "mm_captain.h"
#include "mm_chat.h"
#include "mm_combat_heatmap.h"
#include "mm_debug.h"
#include "mm_freezetag.h"
#include "mm_gametype.h"
#include "mm_ghost.h"
#include "mm_horde.h"
#include "mm_items_rules.h"
#include "mm_loc.h"
#include "mm_maps.h"
#include "mm_match.h"
#include "mm_menu.h"
#include "mm_motd.h"
#include "mm_nav_bake.h"
#include "mm_pconfig.h"
#include "mm_ruleset.h"
#include "mm_ruleset_weapons.h"
#include "mm_scoring.h"
#include "mm_skin.h"
#include "mm_duel.h"
#include "mm_spawn_filter.h"
#include "mm_spawn_loadout.h"
#include "mm_statusbar.h"
#include "mm_strike.h"
#include "mm_team.h"
#include "mm_vote.h"
#include "mm_vote_menu.h"
