// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.

#include "g_local.h"
#include "muffmode/mm_command_contracts.h"
#include "muffmode/mm_pconfig.h"
#include "muffmode/mm_parse.h"

#include <filesystem>

//=======================================================================
// PLAYER CONFIGS
//=======================================================================

namespace {
constexpr long MM_MAX_PLAYER_CONFIG_FILE_LENGTH = 0x40000;

bool MM_IsSafeSocialIdChar(char c) {
	return (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') ||
		(c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.';
}

bool MM_RequirePConfigCommandArgc(gentity_t *ent, int min_expected, int max_expected, const char *usage)
{
	if (MM_IsArgcInRangeValid(gi.argc(), min_expected, max_expected))
		return true;

	gi.LocClient_Print(ent, PRINT_HIGH, "Usage: {}\n", usage);
	return false;
}

bool MM_RequireNoPConfigCommandArgs(gentity_t *ent)
{
	return MM_RequirePConfigCommandArgc(ent, 1, 1, gi.argv(0));
}

bool MM_EnsurePConfigDirectory()
{
	const std::filesystem::path dir("baseq2/pcfg");
	std::error_code error;

	std::filesystem::create_directories(dir, error);
	if (error) {
		gi.Com_PrintFmt("{}: Cannot create player config directory \"{}\": {}\n", __FUNCTION__, dir.string(), error.message());
		return false;
	}

	error.clear();
	if (!std::filesystem::is_directory(dir, error)) {
		gi.Com_PrintFmt("{}: Player config path is not a directory: \"{}\"\n", __FUNCTION__, dir.string());
		return false;
	}

	return true;
}
} // namespace

/*
=============
MM_ClientInitPConfig

Load or create the player's configuration file on connect.
=============
*/
void MM_ClientInitPConfig(gentity_t *ent) {
	bool file_exists = false;
	bool cfg_valid = true;

	if (!ent->client) return;
	if (ent->svflags & SVF_BOT) return;

	// Validate and sanitize social_id for filesystem use
	// This prevents crashes from empty or malicious social_id values
	char safe_social_id[MAX_INFO_VALUE] = {0};
	if (!ent->client->pers.social_id[0]) {
		// Empty social_id - use a fallback based on client number
		Q_strlcpy(safe_social_id, G_Fmt("unknown_{}", ent - g_entities - 1).data(), sizeof(safe_social_id));
	} else {
		// Sanitize: remove path separators and other dangerous characters
		const char *src = ent->client->pers.social_id;
		char *dst = safe_social_id;
		size_t remaining = sizeof(safe_social_id) - 1;

		while (*src && remaining > 0) {
			char c = *src++;
			// Allow alphanumeric, dash, underscore, and common ID characters.
			// Skip leading dots to avoid ambiguous Windows device/path spellings.
			if (MM_IsSafeSocialIdChar(c) && (c != '.' || dst != safe_social_id)) {
				*dst++ = c;
				remaining--;
			}
		}

		while (dst > safe_social_id && dst[-1] == '.')
			dst--;
		*dst = '\0';

		// If sanitization removed everything, use fallback
		if (!safe_social_id[0]) {
			Q_strlcpy(safe_social_id, G_Fmt("invalid_{}", ent - g_entities - 1).data(), sizeof(safe_social_id));
		}
	}

	const std::string path = std::string(G_Fmt("baseq2/pcfg/{}.cfg", safe_social_id));
	const char *name = path.c_str();

	if (!MM_EnsurePConfigDirectory())
		return;

	FILE *f = fopen(name, "rb");
	char *buffer = nullptr;
	if (f != NULL) {
		size_t length = 0;

		if (fseek(f, 0, SEEK_END) != 0) {
			cfg_valid = false;
		}

		const long file_length = cfg_valid ? ftell(f) : -1;
		if (cfg_valid && file_length < 0) {
			cfg_valid = false;
		} else if (cfg_valid && file_length > MM_MAX_PLAYER_CONFIG_FILE_LENGTH) {
			cfg_valid = false;
		}

		if (cfg_valid) {
			length = static_cast<size_t>(file_length);
			if (fseek(f, 0, SEEK_SET) != 0)
				cfg_valid = false;
		}

		if (cfg_valid) {
			buffer = (char *)gi.TagMalloc(length + 1, '\0');
			if (length) {
				const size_t read_length = fread(buffer, 1, length, f);

				if (length != read_length) {
					cfg_valid = false;
				}
			}

			buffer[length] = '\0';
		}
		file_exists = true;
		fclose(f);

		if (!cfg_valid) {
			if (buffer) {
				gi.TagFree(buffer);
			}
			gi.Com_PrintFmt("{}: Player config load error for \"{}\", discarding.\n", __FUNCTION__, name);
			return;
		}

		if (buffer) {
			gi.TagFree(buffer);
			buffer = nullptr;
		}
	}

	if (!file_exists) {
		f = fopen(name, "wb");
		if (f) {
			const std::string header = std::string(G_Fmt("// {}'s Player Config\n// Generated by Muff Mode\n", ent->client->resp.netname));

			if (fwrite(header.c_str(), 1, header.length(), f) == header.length())
				gi.Com_PrintFmt("{}: Player config written to: \"{}\"\n", __FUNCTION__, name);
			else
				gi.Com_PrintFmt("{}: Player config write error: \"{}\"\n", __FUNCTION__, name);
			fclose(f);
		} else {
			gi.Com_PrintFmt("{}: Cannot save player config: {}\n", __FUNCTION__, name);
		}
	} else {
		//gi.Com_PrintFmt("{}: Player config not saved as file already exists: \"{}\"\n", __FUNCTION__, name);
	}
}

/*
=================
MM_CmdCrosshairID
=================
*/
void MM_CmdCrosshairID(gentity_t *ent) {
	if (!MM_RequireNoPConfigCommandArgs(ent))
		return;

	ent->client->sess.pc.show_id ^= true;
	gi.LocClient_Print(ent, PRINT_HIGH, "Player identification display: {}\n", ent->client->sess.pc.show_id ? "ON" : "OFF");
}

/*
=================
MM_CmdTimer
=================
*/
void MM_CmdTimer(gentity_t *ent) {
	if (!MM_RequireNoPConfigCommandArgs(ent))
		return;

	ent->client->sess.pc.show_timer ^= true;
	gi.LocClient_Print(ent, PRINT_HIGH, "Match timer display: {}\n", ent->client->sess.pc.show_timer ? "ON" : "OFF");
}

/*
=================
MM_CmdFragMessages
=================
*/
void MM_CmdFragMessages(gentity_t *ent) {
	if (!MM_RequireNoPConfigCommandArgs(ent))
		return;

	ent->client->sess.pc.show_fragmessages ^= true;
	gi.LocClient_Print(ent, PRINT_HIGH, "{} frag messages.\n", ent->client->sess.pc.show_fragmessages ? "Activating" : "Disabling");
}

/*
=================
MM_CmdAnnouncer
=================
*/
void MM_CmdAnnouncer(gentity_t *ent) {
	if (!MM_RequireNoPConfigCommandArgs(ent))
		return;

	ent->client->sess.pc.use_expanded ^= true;
	gi.LocClient_Print(ent, PRINT_HIGH, "Match announcer: {}\n", ent->client->sess.pc.use_expanded ? "ON" : "OFF");
}

/*
=================
MM_CmdKillBeep
=================
*/
void MM_CmdKillBeep(gentity_t *ent) {
	if (!MM_RequirePConfigCommandArgc(ent, 1, 2, G_Fmt("{} [0-4]", gi.argv(0)).data()))
		return;

	int num = 0;
	if (gi.argc() > 1) {
		const auto parsed = MM_ParseNonNegativeIntArg(gi.argv(1));
		if (!parsed || *parsed > 4) {
			gi.LocClient_Print(ent, PRINT_HIGH, "Invalid kill beep value. Use 0 through 4.\n");
			return;
		}
		num = *parsed;
	} else {
		num = (ent->client->sess.pc.killbeep_num + 1) % 5;
	}
	const char *sb[5] = { "off", "clang", "beep-boop", "insane", "tang-tang" };
	ent->client->sess.pc.killbeep_num = num;
	gi.LocClient_Print(ent, PRINT_HIGH, "Kill beep changed to: {}\n", sb[num]);
}
