// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.

#include "g_local.h"
#include "muffmode/mm_pconfig.h"
#include "muffmode/mm_parse.h"

//=======================================================================
// PLAYER CONFIGS
//=======================================================================
/*
=============
MM_ClientInitPConfig

Load or create the player's configuration file on connect.
=============
*/
void MM_ClientInitPConfig(gentity_t *ent) {
	bool file_exists = false;
	bool cfg_valid = true;

	if (!ent->client) return;
	if (ent->svflags & SVF_BOT) return;

	// Validate and sanitize social_id for filesystem use
	// This prevents crashes from empty or malicious social_id values
	char safe_social_id[MAX_INFO_VALUE] = {0};
	if (!ent->client->pers.social_id[0]) {
		// Empty social_id - use a fallback based on client number
		Q_strlcpy(safe_social_id, G_Fmt("unknown_{}", ent - g_entities - 1).data(), sizeof(safe_social_id));
	} else {
		// Sanitize: remove path separators and other dangerous characters
		const char *src = ent->client->pers.social_id;
		char *dst = safe_social_id;
		size_t remaining = sizeof(safe_social_id) - 1;

		while (*src && remaining > 0) {
			char c = *src++;
			// Allow alphanumeric, dash, underscore, and common ID characters
			// Block path separators, null bytes, and other filesystem-unsafe chars
			if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') ||
			    (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.') {
				*dst++ = c;
				remaining--;
			}
		}
		*dst = '\0';

		// If sanitization removed everything, use fallback
		if (!safe_social_id[0]) {
			Q_strlcpy(safe_social_id, G_Fmt("invalid_{}", ent - g_entities - 1).data(), sizeof(safe_social_id));
		}
	}

	const std::string path = std::string(G_Fmt("baseq2/pcfg/{}.cfg", safe_social_id));
	const char *name = path.c_str();

	FILE *f = fopen(name, "rb");
	char *buffer = nullptr;
	if (f != NULL) {
		size_t length;
		size_t read_length;

		fseek(f, 0, SEEK_END);
		length = ftell(f);
		fseek(f, 0, SEEK_SET);

		if (length > 0x40000) {
			cfg_valid = false;
		}
		if (cfg_valid) {
			buffer = (char *)gi.TagMalloc(length + 1, '\0');
			if (length) {
				read_length = fread(buffer, 1, length, f);

				if (length != read_length) {
					cfg_valid = false;
				}
			}
		}
		file_exists = true;
		fclose(f);

		if (!cfg_valid) {
			if (buffer) {
				gi.TagFree(buffer);
			}
			gi.Com_PrintFmt("{}: Player config load error for \"{}\", discarding.\n", __FUNCTION__, name);
			return;
		}

		if (buffer) {
			gi.TagFree(buffer);
			buffer = nullptr;
		}
	}

	if (!file_exists) {
		f = fopen(name, "w");
		if (f) {
			const std::string header = std::string(G_Fmt("// {}'s Player Config\n// Generated by Muff Mode\n", ent->client->resp.netname));

			fwrite(header.c_str(), 1, header.length(), f);
			gi.Com_PrintFmt("{}: Player config written to: \"{}\"\n", __FUNCTION__, name);
			fclose(f);
		} else {
			gi.Com_PrintFmt("{}: Cannot save player config: {}\n", __FUNCTION__, name);
		}
	} else {
		//gi.Com_PrintFmt("{}: Player config not saved as file already exists: \"{}\"\n", __FUNCTION__, name);
	}
}

/*
=================
MM_CmdCrosshairID
=================
*/
void MM_CmdCrosshairID(gentity_t *ent) {
	ent->client->sess.pc.show_id ^= true;
	gi.LocClient_Print(ent, PRINT_HIGH, "Player identication display: {}\n", ent->client->sess.pc.show_id ? "ON" : "OFF");
}

/*
=================
MM_CmdTimer
=================
*/
void MM_CmdTimer(gentity_t *ent) {
	ent->client->sess.pc.show_timer ^= true;
	gi.LocClient_Print(ent, PRINT_HIGH, "Match timer display: {}\n", ent->client->sess.pc.show_timer ? "ON" : "OFF");
}

/*
=================
MM_CmdFragMessages
=================
*/
void MM_CmdFragMessages(gentity_t *ent) {
	ent->client->sess.pc.show_fragmessages ^= true;
	gi.LocClient_Print(ent, PRINT_HIGH, "{} frag messages.\n", ent->client->sess.pc.show_fragmessages ? "Activating" : "Disabling");
}

/*
=================
MM_CmdAnnouncer
=================
*/
void MM_CmdAnnouncer(gentity_t *ent) {
	ent->client->sess.pc.use_expanded ^= true;
	gi.LocClient_Print(ent, PRINT_HIGH, "Match announcer: {}\n", ent->client->sess.pc.use_expanded ? "ON" : "OFF");
}

/*
=================
MM_CmdKillBeep
=================
*/
void MM_CmdKillBeep(gentity_t *ent) {
	int num = 0;
	if (gi.argc() > 1) {
		const auto parsed = MM_ParseIntArg(gi.argv(1));
		if (!parsed) {
			gi.LocClient_Print(ent, PRINT_HIGH, "Invalid kill beep value.\n");
			return;
		}
		num = *parsed;
		if (num < 0)
			num = 0;
		else if (num > 4)
			num = 4;
	} else {
		num = (ent->client->sess.pc.killbeep_num + 1) % 5;
	}
	const char *sb[5] = { "off", "clang", "beep-boop", "insane", "tang-tang" };
	ent->client->sess.pc.killbeep_num = num;
	gi.LocClient_Print(ent, PRINT_HIGH, "Kill beep changed to: {}\n", sb[num]);
}
