<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(MMEnableAddressSanitizer)'=='true'">
    <WholeProgramOptimization>false</WholeProgramOptimization>
  </PropertyGroup>

  <ItemDefinitionGroup Condition="'$(MMTreatWarningsAsErrors)'=='true'">
    <ClCompile>
      <TreatWarningAsError>true</TreatWarningAsError>
    </ClCompile>
  </ItemDefinitionGroup>

  <ItemDefinitionGroup Condition="'$(MMRunCodeAnalysis)'=='true'">
    <ClCompile>
      <EnablePREfast>true</EnablePREfast>
    </ClCompile>
  </ItemDefinitionGroup>

  <ItemDefinitionGroup Condition="'$(MMEnableProfileCounters)'=='true'">
    <ClCompile>
      <PreprocessorDefinitions>MM_ENABLE_PROFILE_COUNTERS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>

  <ItemDefinitionGroup Condition="'$(MMUseTracy)'=='true'">
    <ClCompile>
      <PreprocessorDefinitions>MM_USE_TRACY;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>

  <ItemDefinitionGroup Condition="'$(MMEnableAddressSanitizer)'=='true'">
    <ClCompile>
      <PreprocessorDefinitions>_DISABLE_VECTOR_ANNOTATION;_DISABLE_STRING_ANNOTATION;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <BasicRuntimeChecks>Default</BasicRuntimeChecks>
    </ClCompile>
    <Link>
      <LinkIncremental>false</LinkIncremental>
    </Link>
  </ItemDefinitionGroup>

  <ItemDefinitionGroup Condition="'$(MMEnableUndefinedSanitizer)'=='true'">
    <ClCompile>
      <AdditionalOptions>-fsanitize=undefined -fno-sanitize-recover=undefined %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <Link>
      <AdditionalOptions>-fsanitize=undefined %(AdditionalOptions)</AdditionalOptions>
    </Link>
  </ItemDefinitionGroup>
</Project>
